doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                type: attribute
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                is_bundle: false
                prefix: App\User\Domain\Entity
                alias: App
            
            Dispenser:
                type: attribute
                dir: '%kernel.project_dir%/src/Dispenser/Domain/Entity'
                is_bundle: false
                prefix: App\Dispenser\Domain\Entity
                alias: App
