<?php

namespace App\Tests\Unit\Dispenser\Application\Command\CloseDispenser;

use App\Dispenser\Application\Command\CloseDispenser\CloseDispenserCommandHandler;
use App\Dispenser\Domain\Bus\Command\CloseDispenser\CloseDispenserCommand;
use App\Dispenser\Domain\Persistence\Repository\DispenserRepositoryInterface;
use App\Shared\Domain\Bus\Event\EventBusInterface;
use App\Tests\Unit\Dispenser\Domain\Entity\DispenserMother;
use PHPUnit\Framework\TestCase;

class CloseDispenserCommandHandlerTest extends TestCase
{
    private CloseDispenserCommandHandler $classUnderTest;
    private DispenserRepositoryInterface $dispenserRepositoryMock;
    private EventBusInterface            $eventBusMock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->dispenserRepositoryMock = $this->createMock(DispenserRepositoryInterface::class);
        $this->eventBusMock            = $this->createMock(EventBusInterface::class);

        $this->classUnderTest = new CloseDispenserCommandHandler(
            $this->dispenserRepositoryMock,
            $this->eventBusMock
        );
    }

    public function testInvokeShouldCloseDispenser(): void
    {
        $dispenser = DispenserMother::random();

        $this->dispenserRepositoryMock
            ->expects($this->once())
            ->method('findById')
            ->willReturn($dispenser);

        $this->classUnderTest->__invoke(
            new CloseDispenserCommand(
                dispenserId: 'anUuid'
            )
        );

        $this->assertTrue(!$dispenser->isOpen());
    }

    public function testCloseDispenserShouldThrowExceptionWhenDispenserNotFound(): void
    {
        $this->dispenserRepositoryMock
            ->expects($this->once())
            ->method('findById')
            ->willReturn(null);

        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('Error opening dispenser');

        $this->classUnderTest->__invoke(
            new CloseDispenserCommand(
                dispenserId: 'anUuid'
            )
        );
    }
}
