Create:
    path: /
    controller: App\Dispenser\Infrastructure\EntryPoint\Api\Create\CreateDispenserController
    methods: [POST]

ChangeStatus:
    path: /{id}/status
    controller: App\Dispenser\Infrastructure\EntryPoint\Api\Status\ChangeDispenserStatusController
    methods: [PUT]
    
Spending:
    path: /{id}/spending
    controller: App\Dispenser\Infrastructure\EntryPoint\Api\Spending\DispenserSpendingController
    methods: [GET]

Docs:
    path: /docs
    controller: App\Dispenser\Infrastructure\EntryPoint\Api\ApiDocumentationController
    methods: [ GET ]
