<?php

namespace App\Tests\Application\Dispenser\Open;

use App\DataFixtures\ApplicationDataFixtures;
use App\Dispenser\Domain\Entity\Dispenser;
use App\Dispenser\Domain\Persistence\Repository\DispenserRepositoryInterface;
use App\User\Domain\Entity\User;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class OpenDispenserTest extends WebTestCase
{
    private KernelBrowser $client;

    private User $user;

    private Dispenser $dispenser;
    private DispenserRepositoryInterface $dispenserRepository;

    protected function setUp(): void
    {
        parent::setUp();
        $this->client        = static::createClient();
        $entityManager = $this->getContainer()->get('doctrine');
        $this->dispenserRepository = $entityManager->getRepository(Dispenser::class);
        $this->dispenser = $this->dispenserRepository->findById(ApplicationDataFixtures::DISPENSER_ID_CLOSED);
        $this->user      = $entityManager->getRepository(User::class)->findOneBy(['email' => ApplicationDataFixtures::USER_EMAIL_OPENED]);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $dispenser = $this->dispenserRepository->findById($this->dispenser->getId());
        $dispenser->close();
        $this->dispenserRepository->save($dispenser);
    }

    public function testOpenDispenserReturnsOk(): void
    {

        $this->client->setServerParameter('HTTP_AUTHORIZATION', 'Bearer ' . $this->user->getApiToken());

        $payload = [
            'dispenser_id' => $this->dispenser->getId(),
        ];

        $this->client->request('POST', '/api/dispenser/open', [], [], [
            'CONTENT_TYPE' => 'application/json'
        ], json_encode($payload));

        $this->assertResponseIsSuccessful();
    }
}
