services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
    
    App\Dispenser\Application\Command\ChangeStatus\ChangeStatusCommandHandler:
        class: App\Dispenser\Application\Command\ChangeStatus\ChangeStatusCommandHandler
        tags: [ 'messenger.message_handler' ]
    
    App\Dispenser\Application\Event\DispenserOpened\CreateDispenserSpendingLineOnDispenserOpenedEventHandler:
        class: App\Dispenser\Application\Event\DispenserOpened\CreateDispenserSpendingLineOnDispenserOpenedEventHandler
        tags: [ 'messenger.message_handler' ]
    
    App\Dispenser\Application\Event\DispenserClosed\FinishDispenserSpendingLineOnDispenserClosedEventHandler:
        class: App\Dispenser\Application\Event\DispenserClosed\FinishDispenserSpendingLineOnDispenserClosedEventHandler
        tags: [ 'messenger.message_handler' ]
    
    App\Dispenser\Application\Query\Spending\DispenserSpendingQueryHandler:
        class: App\Dispenser\Application\Query\Spending\DispenserSpendingQueryHandler
        tags: [ 'messenger.message_handler' ]
